export const ROLE_TICKET_MAPPINGS = [
  {
    role: "IT Support Engineer",
    issue: "Incident (INC)",
    request: "RITM",
    change: "Change Request (CR)",
  },
  {
    role: "Software Developer",
    issue: "Bug Report",
    request: "Feature Request",
    change: "Code Change / PR",
  },
  {
    role: "UX/UI Designer",
    issue: "Design Bug",
    request: "Design Request",
    change: "Revision Request",
  },
  {
    role: "Graphic Designer",
    issue: "Asset Error",
    request: "Design Brief",
    change: "Revision Order",
  },
  {
    role: "Web Developer",
    issue: "Site Issue",
    request: "Build Request",
    change: "Scope Change",
  },
  {
    role: "DevOps / Cloud Engineer",
    issue: "Outage Alert",
    request: "Infra Request",
    change: "Config Change",
  },
  {
    role: "Cybersecurity Analyst",
    issue: "Security Alert",
    request: "Audit Request",
    change: "Policy Change",
  },
  {
    role: "Data Scientist / Analyst",
    issue: "Data Anomaly",
    request: "Analysis Request",
    change: "Model Update",
  },
  {
    role: "AI/ML Engineer",
    issue: "Model Error",
    request: "Training Request",
    change: "Pipeline Change",
  },
  {
    role: "Mobile App Developer",
    issue: "App Crash",
    request: "Feature Request",
    change: "Build Update",
  },
  {
    role: "Content Writer / Copywriter",
    issue: "Content Error",
    request: "Writing Brief",
    change: "Copy Revision",
  },
  {
    role: "SEO Specialist",
    issue: "Ranking Drop",
    request: "Optimization Request",
    change: "Strategy Change",
  },
  {
    role: "Social Media Manager",
    issue: "Post Issue",
    request: "Campaign Request",
    change: "Content Revision",
  },
  {
    role: "Digital Marketing Specialist",
    issue: "Ad Issue",
    request: "Campaign Brief",
    change: "Campaign Change",
  },
  {
    role: "Video Editor",
    issue: "Edit Error",
    request: "Edit Request",
    change: "Revision Cut",
  },
  {
    role: "Photographer / Videographer",
    issue: "Shoot Issue",
    request: "Shoot Request",
    change: "Retake / Reshoot",
  },
  {
    role: "Illustrator / Artist",
    issue: "Artwork Error",
    request: "Commission Request",
    change: "Artwork Revision",
  },
  {
    role: "3D Artist / Animator",
    issue: "Render Error",
    request: "Animation Brief",
    change: "Scene Change",
  },
  {
    role: "Music Producer / Audio Engineer",
    issue: "Audio Issue",
    request: "Track Request",
    change: "Mix Revision",
  },
  {
    role: "Teacher / Tutor",
    issue: "Session Issue",
    request: "Class Request",
    change: "Curriculum Change",
  },
  {
    role: "eLearning Developer",
    issue: "Course Bug",
    request: "Module Request",
    change: "Content Update",
  },
  {
    role: "Translator / Interpreter",
    issue: "Translation Error",
    request: "Translation Brief",
    change: "Terminology Change",
  },
  {
    role: "Virtual Assistant",
    issue: "Task Blocker",
    request: "Task Request",
    change: "Priority Change",
  },
  {
    role: "Project Manager",
    issue: "Risk / Issue Log",
    request: "Deliverable Request",
    change: "Scope Change",
  },
  {
    role: "Business Consultant",
    issue: "Engagement Issue",
    request: "Advisory Request",
    change: "Strategy Revision",
  },
  {
    role: "Financial Advisor / Accountant",
    issue: "Report Error",
    request: "Report Request",
    change: "Amendment",
  },
  {
    role: "Legal / Contract Writer",
    issue: "Clause Dispute",
    request: "Draft Request",
    change: "Contract Revision",
  },
  {
    role: "HR Consultant",
    issue: "Policy Issue",
    request: "HR Request",
    change: "Policy Revision",
  },
  {
    role: "Architect / CAD Designer",
    issue: "Drawing Error",
    request: "Design Brief",
    change: "Plan Revision",
  },
  {
    role: "Interior Designer",
    issue: "Design Conflict",
    request: "Concept Request",
    change: "Layout Change",
  },
  {
    role: "Event Planner",
    issue: "Event Issue",
    request: "Event Brief",
    change: "Plan Amendment",
  },
  {
    role: "PR / Communications Specialist",
    issue: "Crisis Alert",
    request: "PR Brief",
    change: "Messaging Change",
  },
  {
    role: "Customer Support Agent",
    issue: "Support Ticket",
    request: "New Query",
    change: "Escalation Update",
  },
  {
    role: "Life / Business Coach",
    issue: "Session Issue",
    request: "Coaching Request",
    change: "Goal Revision",
  },
  {
    role: "Fitness / Wellness Trainer",
    issue: "Health Concern",
    request: "Program Request",
    change: "Plan Adjustment",
  },
];
